{{- if .Values.helmAlert.enabled -}}
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: {{ include "api-gateway-service.fullname" . }}-dispatch
  namespace: default
spec:
  providerRef:
    name: {{ .Values.helmAlert.provider }}
  summary: "env=dev"
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name:  {{ include "api-gateway-service.fullname" . }}
      namespace: default
  inclusionList:
    - ".*.upgrade.*succeeded.*"
{{- end }}
