apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway-service
  namespace: default
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
  chart:
    spec:
      chart: api-gateway-service
      version: "0.1.0-BUILD.20251229095930" # {"$imagepolicy": "default:api-gateway-service-image-policy:tag"}
      sourceRef:
        kind: HelmRepository
        name: application
  interval: 15s
  values:
    imageUpdateAutomation:
      enabled: true
      image: ghcr.io/skyglass/cloud-native-template-steps/charts/api-gateway-service
      policy:
        semver:
          range: ">0.1.0-BUILD <0.2.0-BUILD"
