apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:W9JMNaWjpPkHJyriUINbYSSvXbLFJ8qdspc2yICaRKKz34ekmIP8FR0/UiPlU67ElcGNYxqLxvQdzJgsL3Sk+T34a3nuI1cJshmaaPJ/cGr315Mnt8GdY+0RoOox5NP0cBFvq5cB/ylsnXkY+y/CLU/HCeqdRmsDOF1Vwr8pv0/RjXv3T3ZYYNk+46z3dM8wBz4AEkZeQkS6FlKW2M9VfdP166xHF3vQn6EAlSHeceriobJU61iOGGOdvPVqj/Ic7xZS77RUwQ6ey17S90f03AUzn/3767Zh35MAv77DYZb/3/ImUJI2Bph0TFf2n7cKiweVRdcfCifZwsH6pQ7v3gqKG17i/cdJa5AihdaDlCiNqR6EKmR+/z/wJTr7n0O3,iv:gi4vAfPShEZfd83CylP0LzR8iP/s8cITm3bnRZwa+8U=,tag:ILnWDC/V4C1MS1EGLVUWpA==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMFlia3ZMOW42cEZRYUdS
            Y3hKR25TQXl6MmtzQWhVVHB5aTVGYkIrUHlNCjBVZjJGWWNRcVdqRHZCby9QakpS
            SER6OGxCYlNCUG5kZ2xBOEVBYmJCdTQKLS0tIENNd0xRU3BJUE5MZ0dhQ0dVTFQx
            V015Mndjc25LcUFxejdUaFFVb3hKNTAKNQ28VGJxhXIAlua5zmRlvo4HqZj/9X1L
            KHo8Q/rlCNq2fubrBrh8CQKVoUOloKlXjfHMZVyCtyj93zP3w2PoWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T04:56:12Z"
    mac: ENC[AES256_GCM,data:DaLzfgaVTmtehR5D//fKWxiwBsHWm8QYkxXd4XXwNFwf0Kytdw+9tzoG11HTHdQQ+HiZDQcvMiPclD9QNKTVE+2kCbAqWmD0rGUXK8ehU+y6aYpAAcn90Jj+bNFwdVx/HaE+4MgbfQufwTh57sgy2Sk/XavPBpoOZIDW0yVHF/I=,iv:b0qt1OXUMnihut9njsuSJhMA5plGXTjJQIP6a/QgpRk=,tag:5rwjP0vtqEnDmiq/SHRMqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
