apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rS/Whi9wIDQlviS3A/fMHZAWuZsxUFuxFBDiogDYCmKJYXyWppznMLJ5m+eVnoKrbduMQJBMzofTDM09ZfyvkmOvpkbE8jV4GhPYZVA1jSNdsnZufSYTppYfwxxKzDCeF6vivGaE1YPcgsi2Fj9hwaWxO9KQ8M4rkBe4cIIX/Fipl+k60y3Vhyt/dFx1eC2LJOFTAx+Vc6hqsPB25w4VZEZZSV+R0J9OErM0sChoSM4Imiu1mVx1EaX6wbVJ2EwKrsTigxZHVC3CkO9i5i7n+DmiYagYIFbMUe2YJ1KvBQgwvyuVPJ+q0SBxqrmjdQLSLrjHzM5qAxCiTyerh3VpuoHYgWPZS2SaDjJqYxH4elPzmfKastw9aQGCVxTJIe0N,iv:KjUV8PgwJ+wpVTwVXT35KqL6CA3YOw1GL/yvIthYF4k=,tag:m5zvXqwoiadIl8HX353f1w==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM0ZYUmtVbEorZ0kzb3Jv
            OGVxc1lSYzJnbXBISS9yTGdydXRzNFY0clFZCjVzbjZrWmsvWFF3VlZ4bWdKSkU3
            OTdmcGtaL0JnS01jTHFYSk5sV21XcTAKLS0tIFNFQ0IrTFN4Q29FcDI0SVJncHpa
            RzUrU1QvYWFsYmdPVkhXZjAvakl1ZlEKCpJtsMSnpvezcCZsQ10+VDWbUoPPj2Sc
            cQyp6SBil+rpNHePPkbkxGyvsxmn/UlxfMrmyXSF7NUWXydFysEC+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T06:09:20Z"
    mac: ENC[AES256_GCM,data:MYr01D4FjHXfrst1rB19rEtv8kcF+zGd/9BU9iMN4pKAEQJ/gqiuhw/32XDUIAnmd54GXOLVAKsDZhMNMQpX7vJnMGl/p16GbiScQ12kq7/MHuMeFHhiGuvU6ZyPHmdzQompHjX6tW+1aKsTPCKnHoEwIHwzxAZew+xjBFGfl0s=,iv:fGAacWPc9smu5i2X5R7T2a5tJBcssKtjYPerzoHZlPE=,tag:M1bIsrW4FiE9gWYvBIfTcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
