apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:swExS/R891k5NP4MTgeXX6lk0GlB9Bc+n9t7pF2GWHPkUU/pwSl+Iu4xPIvqInQ11eUV4NpV6VRjyLQiks6pun5ZSleD5+rNb3B104cueq78xSL/tljDGng3IBinHg1gesWPqPUEc4KABu0zxtzOB2XjpR4wKMgwa6HWNu1a+PXl5DmDH3DkdBDKiMPvPhu8R99GqmA6gnUB+qu8mzitRhP5+dTvbqsJzm+oxlELSuenVniZSXFPQFzJH9ShyQxhKtpDFj213a/sGjVMeAoHcAB64zB+uZJ6HwQqrU+bym55W8Dhm/WmaL5haFvIdYch2vjIKP7lvPfa8X4PkYsxmiTMJ3swUybcFdXWKChO3/wzKvSboqxMRMy+gZsbS/+N,iv:a9dyc8Bt8qywFzS/6F3BfBk++cNy5ZyqdzWnTUWWwIw=,tag:x0wl/xNdNL4bACLpIot1iQ==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS1h4VmZZVDhLbTFRam9R
            eXFnWDZtM2dZNDVFM0xMamFuZzRJbkc2cDJBCmpmTTBhRXlDdGFBZjEzZnRVZGJh
            UExiMC9LOHR6bFpSLytUcVF0blJTek0KLS0tIFJLOEkvOVVLT2pDT25weG1NOCs5
            KzdZSmNabDdLbk15QndkZmU1K0JIOXMKNjUJv5SGrajRMVfdhdCgobe6iMDHwhPx
            AP5bDJH3bi2r4KabbcnYsEmQXuSWBIq39bgSEBrnaEhfwP2uMVN6+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T08:34:20Z"
    mac: ENC[AES256_GCM,data:AmQYaawsLJNjlQH+MkK6yULvX0oS0Hceuws/9DOECQioKaHnGLnIh7eEZjRpPO4d71GBvz4c5bw530YvFfsgF6mcF10JSmzo0sJlxKgHxIqrTRscge67B05psU1Xu7X5+e9W1a7pueYD4HJxT+R9r+EIVXo84A5lx/C3//JU7BM=,iv:lwiIud0GZJTkrX8YqNd16g798drpwY3xNCidHYrbN4M=,tag:aJZlERBO6Ql4Ar8qpoqhOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
