apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CDs06az+V4lHJD3pd71kNz9vYR8pbd6L+MSdrI3l78mSVBA0W1IeGKtrxF/2vDsfi4oIkGlcsGaOHg7i8x4f9jtHIX4p2p4fKz+CZJAhMbh7vrXbYTGHl3iZpR1H/ZcZvkCJ7tzofn3chOPdH6CK8ycZk5l7meKWlqqINGyteJ94f5onSi/w8b+Z/qEo8Ki/xh4YR6oRPuCmiGdULFBuwlzsPe5pR4MaDyEj4sH6R0sBttLKNk5t0br5GWAbUVTLEZPsQ9cp3BRqLwm5iZmiHLNUbpGWiDhZGxEgH3q/z2OjxjBYxl6reCir9fBgb/1LwAywU8wlntwGRJ7bZrJLq/WWH6yom+dngiviVMa7zygwq0ZXHtATH3ZXB/j5Z8/+,iv:Ajx5fWVBbfjKWB6NeoIYzY+zHxydplQ3jrIARrwNwlg=,tag:123G3XKimcChRnZzLlWzNw==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbzJvei9oaWV5S3lYbktO
            b2tEQ056ZzI2V1hPa2ZweUhVUFN4Yjl4UVZJCldudUcxbGlHSzd2ZW1vdDlNUzJ3
            VU5xbEliRmRzMTZEbEtUVzI0TXBTbzgKLS0tIHFVc01OR1d3czJiTWxOa0Z1Z1hM
            VWNKb3dGUXpYVkRNZXh4c1ZWTUFqQVEK4Bo3xVWD0r2Wgl5BKxwb5uQtWJYUQaED
            wKibQf3Z3hLg0SW/gsm1LlYBLUbKgcYBjbc1ILUN3xIcGq8svi+GsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T11:29:42Z"
    mac: ENC[AES256_GCM,data:YX3aUqVCHnag0Z3eQJqZSwNMJYgV4ZuFrJK/mj3zB+9f5fZlSdPc5nhtnEs8AxKaGENpD4EOEn0oZ06q6SXGbVG2W+qELwC7eD1ZtHZ52+DGIc7Pnoln6X5DyqDfGvrWfqN82fLcSG4wFLIMllLLPr4nXuo6udilN/i9Ge41YTI=,iv:zCbWNXYVoFb5GnY4/4AWdbqod+Vwwv3KB/kUbkbHcdE=,tag:5hBkaf1IRKnf03NiwpQqXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
