apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: default
spec:
  dependsOn:
    - name: kafka
  chart:
    spec:
      chart: order-service
      sourceRef:
        kind: HelmRepository
        name: application
      version: "0.1.0-BUILD.20260102165107" # {"$imagepolicy": "default:order-service-image-policy:tag"}
  interval: 15s
