apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: default
spec:
  dependsOn:
    - name: kafka
  chart:
    spec:
      chart: order-service
      sourceRef:
        kind: HelmRepository
        name: application
      version: "0.1.0-BUILD.20251230070046" # {"$imagepolicy": "default:order-service-image-policy:tag"}
  interval: 15s
  values:
    imageUpdateAutomation:
      enabled: true
      image: ghcr.io/skyglass/cloud-native-template-steps/charts/order-service
      policy:
        semver:
          range: ">0.1.0-BUILD <0.2.0-BUILD"
