apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-storage.yaml
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: kafka
    patch: |
      spec:
        values:
          kafka:
            persistence:
              enabled: true
              size: 10Gi
              storageClassName: kafka-sc
          zookeeper:
            persistence:
              enabled: true
              size: 5Gi
              storageClassName: kafka-sc
