apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-eks
  namespace: default
spec:
  interval: 30s
  dependsOn:
    - name: infrastructure-base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/infrastructure/eks
  prune: true
  wait: true
  timeout: 240s