---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: eventuate
  namespace: default
spec:
  interval: 60s
  url: https://eventuate-platform.github.io/eventuate-helm-charts
