apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  chart:
    spec:
      chart: kafka
      sourceRef:
        kind: HelmRepository
        name: eventuate
      version: "v0.4.0"
      reconcileStrategy: ChartVersion
  interval: 15s
  values:
    kafka:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: kafka-sc
    zookeeper:
      persistence:
        enabled: true
        size: 5Gi
        storageClassName: kafka-sc
