apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  values:
    kafka:
      persistence:
        storageClass: kafka-sc
    zookeeper:
      persistence:
        storageClass: kafka-sc
