apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-kafka
spec:
  volumeClaimTemplates:
    - metadata:
        name: my-kafka-persistent-storage
      spec:
        storageClassName: kafka-sc
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-kafka-zookeeper
spec:
  volumeClaimTemplates:
    - metadata:
        name: my-kafka-zookeeper-persistent-storage
      spec:
        storageClassName: kafka-sc
