apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-storage.yaml
  - AuthorizationServerHelmRelease.yaml
  - KafkaHelmRelease.yaml
  - EventuateHelmRepository.yaml
patches:
  - path: ./KafkaHelmRelease-pvc-patch.yaml
    target:
      kind: HelmRelease
      name: kafka
