apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:i2exlbvkCOnv1bMqOCEwvxyX6pNuWFDX4ZZYoezGkW9G7Mf6nbR3nV/lnHaQ17smdXrOX8Rv7zs5MWm+86S9yNSYAeWo1Y3ZyAPIO5OJSCjLY4d/bLxYqIw6Vrn2wOd8lLcTI8xLdz7S1mMyoNrXerdMaDnUXda22+OVZvyFshbgIKyOaH5p+gzdx5OaZGspXvs7pUSuVOMg/FcIL0AL3gsx7oqUuHlqK08WVMPHk/9OnpbT1edeKJeYJZONowqezKKkkMAQgCXoAIDLa0cECdWbny1oSp6TTI5tMTHUwi6FBsZL07/vI/0kMKqDkd9uCSKmgBfjBK0MNghB66BVdtqHI3YAAHQkV5zctlu3zz+3OgsRD2AxqqHYebx8px79,iv:4JMKrjULLIzbTnf9lJWJWCT5NT76xPldWy7h9lsIZBw=,tag:LpeyW95M9lFEYG4wfgtbdA==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRzh3c09valdUL2VrZllj
            QXM2UkNZUFNKS0pDVVJmZ29oSmhLVHlQNEd3ClM4ODhWblpEMEpwQVEzZkRoakFq
            NWRFcG02MXRlTVRvM0N2bkZGN245RTgKLS0tIFhnVGFGVThTMXVRc3QzNHB2V2t0
            L3BsTUExZFFHSnhGTnhhb2VKMk9EZUkKiEb4EqENVdJK8QtBy69Y3UyaHo7wgbbs
            Tt7yqqVjVOzg3mW0E24+V6O/GHt/vgAC7kE7J8OYdVttBRy/83d8EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T15:34:06Z"
    mac: ENC[AES256_GCM,data:WlOWMb0VmcZUluKW82rzC9iq/gI7REfrzpntpC5liW0ilRgqn873pp0PHpBUhj6BRjnZ49OJbMOfBI0ubn30GKK/T9ACxo2Y3CK/uD/Hj19iByBNcMFmrrXAnwl2H33jb5PcpR2JPo8W4A2vkXlaGjTO2D7uVjuQyJY8gaQbWDM=,iv:9KPxw6/OWTOdHWYi1g7ux0kDvnVFGcdfex0b2jwmbP4=,tag:IyzQp2QZ1ICH8egKe1ZW7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
