apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:NC4UZumo12hREirT2Ag/YTT5wy64obwmbz62ekZyRUjTziwNdGBiEQZgsEZMU6M+gYWoZV1nNWHMK1GZehixyomeR/3oNtIgMtbcDJi8q91FEN4gCTxWdadCnVma2RU4Xo3VGcR7ffyE8/9fei5GBc2si8SFeFCIWDULwuZt/AkDUGYVAUBcKuIMu4zQhH7VTHn74ZDUg1EIHjTHxURAJLhC9uCo+pa+7MH20t5asHsb7SO84J1v3hG5SdZphwZljUpJ+XfdzrAwjOWlbF+DnAdo0wLkjGxSrPvVATgixQm7wOD/r2ehidYI/ySNSgHSjD1vvhCoRphX2JrcqnliOlKee/ZLrcOcQnpnYGd2qRilOxkznn97FKf9UOTCjXBM,iv:/mVqJyxbRV//G2vs9k1vVXtRbsneQgHwcEUnvGdtmG4=,tag:hmAFfLT9R8k6uPoFmmdf4w==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMU9MQkZ3SnNaUlQwOS9J
            ZzdHSjhBWGhiLzJtaGJsSVRFTkdmTGNGaFFzCjR4aWhkQ2ppejB4MHU2TFdnRXN4
            dnJqQjY4L250SlM3Y213Tk9haTBsbjQKLS0tIHZ6TWtjS2hlZjZGM09NQ0h1ZVZt
            Rkp3ay96SjZvT2ZWMUZlb1dBcFMxQ1kKdCrwW14l8xyhAEyIOHZu8gmMV1NFRrYg
            0EYGC43OCgIfYpMeu1AxyEHMT4+hzi9pd1uu6WkbuUGulpyvlruKJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T13:12:22Z"
    mac: ENC[AES256_GCM,data:KVhbNfg7J96Mvnxqq6dW3g9HrXuV8g1b8/yKi968Sv0co++UtF2aLEujxYhWdlDWak/zOAFV2Q8lvyOCmWSxlpAxicrspeY24EM1/+EBirZykGOg9HFqYyiIElEuHzwnv223blKEWif6jNzl2+H+Nlxx8MLIGfw8ySjsSUEBSRo=,iv:7zQpeIUcBqwA3cefh5K0UCHZU5W1m/vpIhqNlWVHjNc=,tag:6QglDee2+DLM86sm+Cn7uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
