apiVersion: v1
data:
    token: ENC[AES256_GCM,data:ddPCb4JDgYi8wP7zH4cASxZQmsZjtQCw3g//ddeFog6bmvSNCY9Z6pBmkha/ets7vj7PxoQ99VE=,iv:jnv6pZi+oaSxy8SIgRe7mz0Sc6CB818GL1Im+bRwm6c=,tag:RGyfbqblFV7q77Qop/6AgA==,type:str]
kind: Secret
metadata:
    name: github-token
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM2UvcmFrSlpMV3dvdm9E
            VTVDZElFZFdJSGhVenBUY2U3Y3F6dmNrQlhZClBGMERFN1h1NDcveVREbzlMS2pE
            L1dzTkllQ1Z5Nk11MGhWdlpBOHVYeE0KLS0tIGJHcjc2ZFk4VStaMWZFaUJKKzdi
            NkdsbDJrN2NsdlZxM3pZQkpmMjV5dkUKa1nlv9lnAl3+u+25ySaZ36YDDo+S1ft7
            2Rair61IivnWGhOBsfg5VysZ1qNYJFHcevyV0xabp8V/yW8WehHfWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T13:27:06Z"
    mac: ENC[AES256_GCM,data:cZjp30EpJI6ADOeimyf5rshqC2/OeJNA+AeL24Yuf4qMRHeI5fPUrfaNyf6dVjOh+3rl2PVbMq/srFiI4ovZHK8wDEdmFV8WMNg6YN3ja6Z01OO+1PoQYAEvR1u3AttVhVhHUmS7mueTN+yDESTlU94a8WBvzJ7z9Jv9690Nazw=,iv:LuV0vNi7XTzkXqooE0uvgeK8itfyh5oj8hck9alHFdA=,tag:0xoJIGsYhiJxQZoJXtFk2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
