apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: default
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20260102125452" # {"$imagepolicy": "default:order-service-image-policy:tag"}
