apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-gateway-service
  namespace: default
spec:
  values:
    replicaCount: 2
  chart:
    spec:
      version: 0.1.0-BUILD.20260101090425
