apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mwKAT55ZyjaS+zEPJTuzbZlQC5i93NfplcWJV1t7PxBJi0AMiC55H0VCX6RrUm8vbQfbcEDwKoKqtfHGsLFyTdswpZVewr6eJjvT02O10xdMsh/X+17wFSNCDGg0YxBy9zTOA9NR7oLxyg0IakkmByqkM06GtdPbI0wZ3ALOdPEqwqzlZNtccTqQa5nJMZ9ApQRtD125QRBhYfxPXJs5ZUI8nw80pWoBFEOy/kjpjAzqwzMKT+2Wc8WN1Mww8M4gMKI3JaU4/NBxYQj0rMHYn3VY6Yjvb4anqM9MYgGmawMyFo+x260WxeMpuL9rR1Z2MwvTjWywNF0dtP4+GrXIKvj+YX/hs61P1yTaC2qXkCtdwoxQm3ETmVunOOuhYqO3,iv:GaklqDJ9N41P19GQizk67Cbooey5qfQnQu7MohuWXto=,tag:F6SwFm4ivueUETtVP8Me8w==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbER4QXF2Q0IxSStZYS9x
            YXZNMHFVTnFSMDRzNGVkVFI5Y2pzTzJ0Y1U0CkNlcFRwN3kvMXRubUxXWDBDbEdM
            TmJNZ0RnVHNOeXlkV29zdE5YaUZVbmMKLS0tIHowTitrcUx1ZUJqdEkrS0FudHBh
            NHVLRFI3NGlFNThWZXY1SkFnVy9FZGMKZ5AdxVS3A4PXIE8NPi+qEX428l3B16PH
            o1QwJF+n9XTDQq2M1e6JBhoEHT3/ODACujK7fUPI8++T4pWC7qyRQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T08:51:38Z"
    mac: ENC[AES256_GCM,data:ILeUmkDABm3R8KtS/313FmRn0OFuVVt1LJLnXrp+htcGkkgnMYEmlEn4vDnZVyPnF8YergdXOMeVWfk5olEup+6M4a535VyTQ/MFoh4Ice0aL2j/mS1piIpfSX/x+2l4QK3zPAfG5QPp/IpAe3Cd4hD9w+njrqEF8N+CnVlRIrQ=,iv:URcwpMq2hNrjda56mAxndJgJTkL194sSkGuYM4KAr60=,tag:LDRSv/xCvrvxE9oII1i22A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
