apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:X4ObBQZaaJUQLtVwwS4ukt8K8PlWRJkR0EW3tbMkvGvxT+DNmQ8eOUQrTNstd4Wo3H1t7n4oQPjFEG1Vx3IqOpBIrgmnSMmsfegQ2yrEio/VUnYzwQtBt5ads/jXcK/XnB+22i84xgKZ0blx/5N36CroWdDBTSLZp9pNd7Dti0lACLFHN0yvR7qIsj1wO/mKRfpDnbLLJOvEibz9ZTEAopAWzZlhHcVm8AzErPksiRIhPlfi5Its+26sG3qfK4R/CYPlcgRrslXcaWzBSgRH8JY8Qx2IuBkokk1+XtS8RD8JMFVrgSxOu+Kv5DOznv2si5AV7/CiSFwdoiy0bE1TjXEqKKGmln7BEJtjW+x895EN8Vu7xzTtoatjUCIlBskR,iv:9HIE7WKaHDf1/vnupc9J1S+atKuy39p4k4S7n3AwHAY=,tag:UioRJe5A2awKDwj4Aq7jUA==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNGVGN2QySm5WTGVjNjVl
            eWVJbHAwdmFsTXg5Zm5EMGpBQjRpcEY5QmpFCmpFM01pV3d5eUFMc0lVcU5QdkVa
            UEQvQVdZNHdLWDdCT1F2aDJRbE5zZVUKLS0tIFVLS1R2TFk1WmF0bXhLN1pLYTlo
            ZXY0a2F3dW9icmYzbHBvelJrdkpTSDAKP/rg5buQB440vYfPrstjxhEmSizF8srq
            YkAT9/F9Ou1jWmiFE6W5eAjUf6RlL2MPl7mDTTyp5fQV3JPTX/DinQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T13:16:47Z"
    mac: ENC[AES256_GCM,data:c6DuhhLo/uN6T/kjmTpEZ4Bik1ALxglxKkbhAO106OZeOyVaoCbaxE+666ocUZzFILi4iF1cvYE1p1kQdiGFawcyfgEf68uxIF3B5jCMTn50oDdowSpTyjsRD7vUKBCZt9X+/ViU9RkaaDUcGtFECP/6yNMUEs8V5s2v5tE/BPQ=,iv:oK7+nop4Ua0GT9x959iIU0zP8P+npYwgbrL+fkY/rfc=,tag:yXY65iEOgu8QH9hvglLNiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
