apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Bz+8HmYJrAqoU273w8vUYbJVsdvJvdKg7mWDssIql0W1GuReG34zavHuzfHTFZdiJ8IxTyzsocqxG11aF7npfu8CadXMkyR5rWaQXxVOjlOXzizExp2wq5buYvmsyCLMK2YL5qfXsxWIxNyxOjaX8lwmBN7u73NsGNhNLXgiIg5Rt2Zp5/IaOon/5KyBfjF56qHKnLAZ4u1Cd7USjtlPDRDDSrH2/7kcYgozY15bCrR92hzKlCjyYrvO+wmeaAPTXsd8WEoOfLzkzvD7s5tYTMEodTi+HlpgDHVv+SR8x8coTQho6/XOEd4T4/vVsP8Vid5AKmeUGy3JQjG45ASnAemDUWuAF5FeVnnstuuXP3QCc5v9AHSCemm0/iEBTwrm,iv:WDCirRxrljRHKdAg3UeKO25vCZT+MyufipZ/mHM+4mE=,tag:cwXQ3BuoIzB/VB3s0UEHbw==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2VCTVNyOHd1Z3hkZmFK
            QUs5ZHZFSnYySWd6V1NUSHlBVjNMN1UzWGx3CjdRZENCalZnWk5kWkp0VWpMZzFp
            aHRaendrVGlZV0FWdnp6WFBpQ1lRUzQKLS0tIHdMTzJiam1uN0xxU1hsRXpSNDE3
            aHlHTlZ4Slh0NDl6RSs4bEkvL2dLVlkKKPYBNeUaDYumXfNlEAlQ9XQYY4trfv/3
            ed8WQ12hjCLvaF3OLiLUHQUS159R8HZEgtq19jFOETIhol2ufWaJYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T16:21:37Z"
    mac: ENC[AES256_GCM,data:l4Cadr9czl/eltItjM6ExvbIs82hUjsmx0BFZlsn77hiAYj40ARkFa7zSbLNiIdjBmgjDrh5zunLk/pt7k/hM927hGLMQOcfzGbNNn0wBFEj1BLiM2v119FE71aULHckyw6z7GPKTS4e59qbJOdmR1cVjvb9NZhk3aB+XXBWWMk=,iv:u8vzuzgdJh9aTz1l8y47flQv0RZIHGasaoCeDSE7MDk=,tag:yLlfrJGOpI4j+X9zOE8t9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
