apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: order-service
  namespace: default
  annotations:
    notification.toolkit.fluxcd.io/subscribe: "true"
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20260102110111" # {"$imagepolicy": "default:order-service-image-policy:tag"}
  values:
    imageUpdateAutomation:
      enabled: true
      image: ghcr.io/skyglass/cloud-native-template-steps/charts/order-service
      policy:
        semver:
          range: ">0.1.0-BUILD <0.2.0-BUILD"
    helmAlert:
      enabled: true
