apiVersion: v1
data:
    token: ENC[AES256_GCM,data:0vKMO9hQpawzY/+S8vPWgvWLTWLUl8HT6Y7rdfXZ7aDhWFyAu17ek7lHTvup1t7bdiag/oT4wtw=,iv:4CdclNn5Tvhaq/rJPWMNp23hhbmGTHKY9IQiYPK7px8=,tag:K0fCELCgPLJZR0BdSL6izA==,type:str]
kind: Secret
metadata:
    name: github-token
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eE1VeU5VY3dtb1A2QVBT
            cUd3aXhXbW1JSC9QaGRkK2VDS25hZUR5U3kwCnVZZVdmRUZRZ2taNXJhMmFEQWdH
            SXZOYkdlQ0wyYTl4WU10RTJvUWErOE0KLS0tIEd4SVRuV0RQY2pwaE5QSEVGQXhB
            WDFveTN3aFJCNGpGRWxZMEFQNGV2R00KBE2OIScwVfRvpdcEfzIjTpKJYsjjKA6e
            E8WPZnskCP9QPl9HWy57FPjhj+SdtiI4iRqLBz16iokxiSCpDBEBBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T15:02:51Z"
    mac: ENC[AES256_GCM,data:yLonrijXDl/pXP3ui97U91cBB5PwkvLg2m6vAtwuwxV7D2J/0WP1jvjNWu064GXzs1BYidxEoCIzBbtsO5NBTt/lrkSaJfnYjP7u8hXjOq13/Ev0EcKiS2/+hI+GEXJ5GlTGRH5aAaWd03z7lquvQxX6DRyAZHucZDzBkuXYPRg=,iv:Ae0NGGIdAyLQe5EkJz71yWBb5N+sw9B0AU212yrGoSs=,tag:gqCjFUZLNlQUJd5SFLvLtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
