apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:79Cwqs9HO1mSfVd/O0n0TzvdTSWM4EQodE8MlAYKCKer6GMXUbibfRgTc0Y0zlQlbsxnxff7jSmOyNI3LbjiMtU7wHQmFZZHA9VTebclwbgDwtfQot/jkQVEYnnHKn6fjX8E06T9ERDg1iYEr4tfKKsQIJcy5OnFId4Am440DwrhXwVdKeXbb3mx9C8DQtCahrSAaGrOaV7WdxYuE044svojr4lHyvtRli+pWaPw4O9H6gLHtsS1Ui4VEJFrgh+/ygutOjKQLr3PxhbB9m2g0EcH+4f8MsMPXwiqdzGdlXvRfJDT0Vu56k0b2QBgs/z6avRrF1CzUm/CrHYTz0mPjc/WNsZwQfBaiwMhkbEFbNoUs4ewMFI4a9NzaT+oKOcA,iv:/ai5duJ13agg2HJdgUj/3rUFx9JOcNFNBQEhXV5ZDE0=,tag:6Rrr+rUgJC8PLtEsHd2RsA==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dDVrYWVRbUt3M1hQTEdO
            ZElCTi9teHBWTFl5ZHVocXFJaVVjQ0oya2o0CmFsSEhiN2Y2TEt0eEVYby9ycjRP
            VkZIUFhySHpaUmNPUUhoK0ZlT1FPVnMKLS0tIDU2RGZEcHMvRWxZd256eFAzMDdk
            WDJ5Q1B0dEh2QnNXTGhXOTl1Q2piK28KNBAvnA0FYeRb0YGVe46biQwVA52Dr9xP
            zIcEIt3fFQKjdv4/FFLmOqjtUrK3HBSXX2gjijUW5LgprmHKVj4OlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T21:20:56Z"
    mac: ENC[AES256_GCM,data:HrmWbcaVACEX2qhlDyCG56LHD0/RPC2aoeVuxMQA2J3DR6SDhlFjvO34beGcyySOBuUFQjah2LkJ06P8juJHXEFWWjvdzpsdvDq+qDNe7JeSDsiuWWSC97e4VYCHwBZNZLpVUVmUzM3MfKQk7mc1CKhqqmjsH4/SubX592Yzh34=,iv:idAkQJXhFExOOHnbQqU5Xp157JO5GyzyEMhlSAxyP1I=,tag:eVNhFTaYY/YmGHc/R+UriA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
