apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:gZ2QcBtd1WmOizSCLv5jIrgtVAaTGc008uvW+BMFArVluHP7jxU8leZeIxXnzL4wRZxDAsWHJyLGPLP7eXvbsZ4y2UTQe08ob3qJam+XGwiVrEz9YRAc85Qvg8vgQuCMss5kWRGeXhByyUX3l5de51WMIj7T56dfe6rCKwpDmruTIRoBimeMqyMTDe/hf54aEN7tSnd8U5orWQTrXV3/gnj+XQSjb3lFtlteX3gBHpzXg9QX0rejpieQV9KSQ0rmqEt3vsrHN8APZX54Pd9xvvd7bbt7H7vuiuzdzCIAPgMa1HLLJLP0v0qV3142ilW8Zqp17IZW6HUOrt6Xb0SHOOLHRKSLYikP3eryLKsCWSYG3vdgzR1PHL+IQBNw8maq,iv:TZ/KUAwrpKvKj48r9bDrLahcgrgLCm20rmEB0CywVqo=,tag:zUY8uZPvpOpJZE8ddUTUug==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDZLQ0RIVTAyLzQvWnNY
            VjhkUmI4ei9CQlBJWlVKLzArUmhqNHZpODN3CjRsaTRydXdBd2NKZjV2VHdEcmo0
            cGhwSHV2Q3FnWHNHdURaMHJrdzY2aGsKLS0tIFB2RXEvSTdMaU9Ga3pOOTYzbHp6
            ekxYQitnM21teFNMeUxUSC9nNjRmM0EKng7EEMEW2uX/te4aHHnETOQ/J9BwCDU7
            zdmxciZGhi/ew2kEbfFIvdIeYIRIlCQDxIrTRrupXWnPRJMD/XGjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T22:21:01Z"
    mac: ENC[AES256_GCM,data:CH8fZFaryIjV78uFs3dxvmid+rr2hlyAdU7Q2u/oVs2vZ4jOZ8pxewEZ0He0pN2m8Fu5EOdcp7U8cl5PRbkXh5mMz9A9VrD7Lm2JuYboZ3Lg65/xuhif8ZLZSAwctgZtkcUyGwALboYaNQCrNpXfdZAsmk/UNS+U3tDQMdi6T9s=,iv:/fHDexyIiPBAQl73j8yqaGstgCJa+9xUp1nYw6IYuaA=,tag:9XZlkxeGZqFDQ+O0V0Rygw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
