apiVersion: v1
data:
    token: ENC[AES256_GCM,data:w8p+AB8I/HF6/RV9l77vaqrKT7pl9DI3ZOJVAPbuHA89BZrCWlQWy9Y3tkZPAtzWb8za0biA76A=,iv:FQt8w73fiidncZxSLESqxAoQr9Yobgj9MkqZYpXg4AU=,tag:JkPVtRDGNAhCktSyct1k9A==,type:str]
kind: Secret
metadata:
    name: github-token
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTXJSMzhUT2l5MkNEdzNV
            RnVkK0ltdFdsWjZMcE1DOXZTWlJONjVpZmhNClhRWWwzWFpPL3k0MnJYMmZiSVlB
            M0xTYjZpelM2SENwMzlCZGpBd1NlMW8KLS0tIGNRT3lhQ0RkZi90VUMrZzREdUow
            QjE0bEwxd0EwSDBpMUtwNyt2S3dGUGsK6/dYwFc+BYLmdVLAuj1nDLS69ONP+ciO
            pDIjxkJPIrlsT7P+9A0mElCF/y+BDMfCje9PKd7csI5KLxaooID8Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:05:24Z"
    mac: ENC[AES256_GCM,data:1mxJId1P4JBVoi0wHoO7IJ0NazhBWgl5fi5+6HpHXjaH8FaGH5PpVc2Y8mdUx5Ghbs+r9vlXu9G/6B5zjP9aPN1SyOY0HLcXw9LrAG+3fBh9WOBK8YcoznHZZBy2JlFulbPKoTThEpxtKRPPfbboiYvFLXYyxRjcrhlxt55xmjQ=,iv:cxAJEP9wYLWTfmGQPMcWK1//n5dRlBYelqXIxLaFxTg=,tag:pxND8lo/iAzfShj4jsxCDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
