apiVersion: v1
data:
    token: ENC[AES256_GCM,data:6Rbcb8Rr1+B1O+qQPEF7XIXSLJvkEsEtr+Uf4QwQUJ7zBYf9abI8EjCa/fH7s0Z8VtUM92RDKNI=,iv:MmKECDT7OaxvJVYvYKOHnpW72SDsuCFz6TOU5MEYhro=,tag:znBQnyVxbWcpiAXoAKrE3A==,type:str]
kind: Secret
metadata:
    name: github-token
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eTI1dXNHaVRycm1KSU1a
            L3cwM25iZFliYm5YNHVFMVNrRlJWalNET0VzCjdmTXhUQUxyT0UvR25EQ2VXWmJo
            cm5PbVp4V1hzek96MUllakx0bkNuYjAKLS0tIEtyL2Z1TERmMFJNdlN4c0xtbDRk
            eUR5TEM3ajJLb0dlQWg5MlFzTkJtcWcKZY2/6juVMsJ3WuaxWiHWP8lfJOD1yJLw
            gMlabchnvZD8bmm3YQtFfkIQhTpCUi/TTOJeKQRjybWst4W6IFPMxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T22:53:12Z"
    mac: ENC[AES256_GCM,data:LlDeepzNtMNIH6Xu1Cpg4KHna+LCyLlLdSOm62pSNMKzGX1NkI455rA7ZzmBdnre2JiUBBCQlNG3iMJXP6a/e5vWJPtP6c2i3Lyow+KXjYi0++x5/R3vZuXVS7nZfolBPtuAKDU9ElsRtTMmvEIbZrfjB9blmHianQkvibajCWc=,iv:XNuAhpq2lOZd0+QGSn4bbZ6vTHA8vnI5mos7tonrobE=,tag:2FPYqL/eyX2PccB4Q2ufDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
