apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:h/OtLF5eaUnKsJx/PQa6CAMuVU6mC5nOHKimjQk3bnYBs4/OK94XfnjGfchYvPfU9UOjPBtj0TweZ40h0cEYewIHCGKUnl2qWn14Q1uXU6jZCplcytcbExvBh5GuE08UblCMxZ6czengPDcz+XN4ry1gAcz34WChtDkvUBb1b6NXjG2HqCrYZgxxWqIeWQofXnL5WnTCB+ffBq8tdD/gsBYlJhVI36w+k/0hSGE/mqE0wBPCmc7ObxJydDcvvX2EiMeXmFFl1vBqAYz8kQCva2FpvHtWaSGt0rP1lBWEDPw5n/mBUsKmNZ3+/4Bpdw2kAj+Q85wJMJLbdIkH74puX7EnIOlIA3eZ9UhZn4GkoKg1DZ97P3UbnyLYRf7QEL0+,iv:O0yFdVmjjyPVCMXvJ513+evGu+dF/qrFS2UU9R1ZiLI=,tag:TNv4Pg9BvsUdh5/61ylQ1w==,type:str]
kind: Secret
metadata:
    name: ghcr.io
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1tp8dzw8qevk4ez9spk6frm2hld8ka8gld5drw283h4yyutjkqqfqfavj7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFLzV0SW1VWW9WRndsVmdy
            aVBDZDlua3BHQllZdkZpTVpha2NGRC8vaVhzCmQwRjRRS3ZaQkFUQ0I3UmtXamcv
            SmRoV2dLdnRuWjA1dVMyMDFQL1MzVlEKLS0tIFZPN05LcnR1eWxqdHkrSXVQSkND
            VGJ4aTVvYklrRkFOeGIwM001dm1jM1UKd83aFiIaI8s3xGKUhFaxaerzx5M6iXtk
            lngblwAg7r8wo7uP2ht2J0ocP2Jst2HG5UUDd2QLY3FlDWcC1JQnig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T23:20:30Z"
    mac: ENC[AES256_GCM,data:JgefNMw6wL7PmdV1YcL2EgO2vHw6GvuGpoxY2Q5eq3VfljzHT+/q7y+TxvqjcKGiJkBzzTOgGYkQ5FPaLoAev2YjwjOWay3drt9jLprS53NNMamPUZrVRvToK54dhicjmQ9gvershLEHoaUYFNIC9UyZeCREd8XfNA42zIXo4QU=,iv:hyfQG6rDKL9TTcZ2umsfzsVWmYujGdRxTm6ZJw5xS/U=,tag:4OUR0sWKvL1OVQ2jXN8J+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
