apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: customer-service
  namespace: default
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20260208183337"
  values:
    service:
      enabled: true # No canary